name: CI
run-name: ${{ github.actor }} run CI
env:
  CC: clang
  CXX: clang++
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install g++ clang make cmake libboost-all-dev nlohmann-json3-dev libcurl4-openssl-dev
      - run: mkdir -p build && cd build && cmake .. && make

